export const RECEIVE_TICKETS = 'RECEIVE_TICKETS'
export const RECEIVE_SINGLE_TICKET = 'RECEIVE_SINGLE_TICKET'
export const TOGGLE_TICKET_CHECKED = 'TOGGLE_TICKET_CHECKED'
export const TOGGLE_QUEUE_CHECKED = 'TOGGLE_QUEUE_CHECKED'
